org: tofagerl
app: kirc-input
service: kirc-input

frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  region: eu-central-1
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReadMessage
          Resource:
            Fn::GetAtt: [Queue, Arn]
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:BatchWriteItem
          Resource: arn:aws:dynamodb:eu-central-1:030483651510:table/kirc

resources:
  Resources:
    Queue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'kirc-input-queue.fifo'
        FifoQueue: true
        ContentBasedDeduplication: true


functions:
  send-message:
    environment:
      QUEUE_URL: { Ref: Queue }
    handler: ./endpoint/endpoint.handler
    events:
      - http:
          path: /messages
          method: post
  processor:
    handler: ./processor/processor.handler
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - Queue
              - Arn
